name:  Docker Push
on: 
  push: 
    branches: [ "Services" ]
  
jobs:
  React-Test:
   
  
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}


        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: ${{ github.run_number }}
          run: |
            docker build -t 512452245356.dkr.ecr.us-east-1.amazonaws.com/mybookstoreapp:$IMAGE_TAG .
            docker push 512452245356.dkr.ecr.us-east-1.amazonaws.com/mybookstoreapp:$IMAGE_TAG

        - name: Deploy to AWS ECS
          id: deploy-ecs
          run: |
           aws ecs update-service --mybookstorecluster --service mybookstoreservice --force-new-deployment   
